### ISSUE TITLE
Integration suddenly doesn't work anymore

### ISSUE THREAD

**Issue by silvanverschuur** [myTselection/youfone_be#15]
I'm using this integration for about a month now. It was working well until I restarted Home Assistant yesterday. I get the following error message:

```
Error while setting up youfone_be platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/youfone_be/sensor.py", line 88, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/youfone_be/sensor.py", line 57, in dry_setup
    await componentData._forced_update()
  File "/config/custom_components/youfone_be/sensor.py", line 121, in _forced_update
    self._user_details = await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/youfone_be/sensor.py", line 121, in <lambda>
    self._user_details = await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/config/custom_components/youfone_be/utils.py", line 55, in login
    assert response.status_code == 200
AssertionError
```

I have tried to remove one of the YouFone accounts and add it again. That did not fix the problem. Any ideas?

BTW: I'm using the NL version of YouFone

**Comment by deeg61** [comment]
I have the same problem. (NL version) Looks like with the new Home Assistant Core 2023.4 update started the problem. Hope there is a fix for it because I use it a lot and it's an excellent adon

**Comment by myTselection** [comment]
Thanks for the feedback, I'll look into it in coming days and I'll test with latest HA.

**Comment by silvanverschuur** [comment]
@deeg61 / @myTselection I'm using Home Assistant v2023.3.1 so I don't think it's related to the latest version of HA

**Comment by deeg61** [comment]
I mentioned it because after I did the update to V2023.4 it stoped working.  I'm sure silvanverschuur will find a solution

**Comment by myTselection** [comment]
Hi, I have been looking into this today. I have also upgraded to HA 2023.4 jsut to make sure.
So far, I don't see any issue. Although I have no NL account, I tried to login to see the youfone.nl flow and in there as well I don't see any deviation yet.

Is this issue still appearing for you after a reload of the integration? Could have been a maintenance at Youfone.nl.

If it would still occur, would any of you be able to share detailed log?
This can be achieved with following setting in `configuration.yaml`:
```
logger:
  default: info
  logs:
    custom_components.youfone_be: debug
```
Please anonymize your logs before sharing. Thanks!

**Comment by deeg61** [comment]
Hi, Thanks for your time to take a look at the problem. I’ve uninstall the integration and did a new install afterwards. Before the new intall  I had 3 youfone  entities to use (who stoped working a few days ago) after the new install they were completly  gone.  I’ve made a debug log and hope this wil lead to a answer.  Thanks you for your support.. Verzonden vanuit Mail voor Windows Van: myTVerzonden: Saturday, April 8, 2023 1:30 PMAan: myTselection/youfone_beCC: deeg61; MentionOnderwerp: Re: [myTselection/youfone_be] Integration suddenly doesn't work anymore (Issue #15) Hi, I have been looking into this today. I have also upgraded to HA 2023.4 jsut to make sure.So far, I don't see any issue. Although I have no NL account, I tried to login to see the youfone.nl flow and in there as well I don't see any deviation yet.Is this issue still appearing for you after a reload of the integration? Could have been a maintenance at Youfone.nl.If it would still occur, would any of you be able to share detailed log?This can be achieved with following setting in configuration.yaml:logger:  default: info  logs:    custom_components.youfone_be: debugPlease anonymize your logs before sharing. Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by silvanverschuur** [comment]
@myTselection In the past I used a custom (home made) python script to fetch the results from Youfone.nl.
I tried to run this script, but this also doesn't work anymore. The HTTP post to the login page returns HTTP 403. They must have changed something so I compared the headers with a 'normal' login using the browser. My script works again after adding the following header:

```
'referer': 'https://my.youfone.nl/login'
```

Maybe you can add this one too (value depending on the NL/BE setting)?

**Comment by myTselection** [comment]
Great, thanks for that info! I will add it

**Comment by silvanverschuur** [comment]
@myTselection Thanks for the quick fix! I've updated the integration to the latest version and everything is working again.

**Comment by deeg61** [comment]
I've did the update and everything works fine now, your'e the best ! Thanks a lot....
